### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by Sem1ra1** [anareaty/obsidian-snippets-templates-and-scripts#1]
Hi. Firstly, I want to say thanks for your snippet. 
I have tested it and it works cool. The only thing I have noticed, after playing around with **Dataview** plugin, that it renders content way faster if you use `dv.markdownTable()` method.
Currently, you're using `dv.table()` (if I understood you .js file correctly) which has a lesser speed when it comes to render. 

Since I'm not an advanced user of Dataview and JS, I'm still trying to understand your code and replace `dv.table` with `dv.markdownTable`. 
I'm trying to merge your Filters with an ability to change values right in the DW table. Here is an example for` dv.markdownTable()`.

https://discord.com/channels/686053708261228577/1262478297896321195/1265264405621510247
And here is an example of the same idea(editing values) with `dv.table`
https://discord.com/channels/686053708261228577/1262478297896321195/1264935449282089050
So in the second example, you can notice big troubles when it comes to render speed. This is the reason why I want to try to change your code.

I hope my feedback will be useful for you.

**Comment by anareaty** [comment]
Thank you, you gave me some great ideas!
You may want to check out the new version [here](https://github.com/anareaty/obsidian-snippets/blob/main/Dataview-interactive-tables/dvit-info-en.md) (I rewrote the code so much I desided to put it separately). This new version uses `dv.markdownTable()`, as you suggested, and also it allows to edit properties directly from the table.

**Comment by Sem1ra1** [comment]
It sounds great. I read description and its very powerful. I'd like to suggest to add some screenshot/gif how it looks in work so people could regard this work as it deserves. За русскую версию отдельное спасибо, приятно что-то на гитхабе почитать в кои-то веки на русском😅
