### ISSUE TITLE
dvIT: customJS is undefined?

### ISSUE THREAD

**Issue by bea-hemm** [anareaty/obsidian-snippets-templates-and-scripts#2]
Hello! I look forward to having this worked out, because your dvIT is everything I could want. However, after setup it tells me that customJS is undefined. What am I missing? interactive-tables.js is downloaded & in my scripts folder, along with the CSS's in their respective folders. 

Thank you already for making this available!

**Comment by bea-hemm** [comment]
I realize now that it is because you're using the customJS plugin. Now that I'm using it, the error is being thrown on renderView

**Comment by anareaty** [comment]
Can you show me the error text?

**Comment by bea-hemm** [comment]
Here you are. I'd attach the console log, but there's nothing coming up there. 
<img width="734" alt="image" src="https://github.com/user-attachments/assets/2ce2e060-2e08-4967-9a1d-504769f3a490">

**Comment by anareaty** [comment]
Okay, it seems to me that CustomJS is working, but the script itself is not loaded. Dit you set up the scripts folder in CustomJS plugin settings?

**Comment by bea-hemm** [comment]
That did it. I was using a hidden folder, and it wasn't finding the contents. Works like a charm, thank you so much for the help!
